# -*- mode: python ; coding: utf-8 -*-
import os

a = Analysis(
    ['Pro.AP22784884.py'],
    pathex=[os.path.abspath(os.path.join('.', '..'))],
    binaries=[],
    datas=[
    ('modelusage/*', 'modelusage'),
    ('modelalign/*', 'modelalign'),
    ('modelcropper/*', 'modelcropper'),
    ('modelchar/*', 'modelchar'),
    ('modelcropper/crop_styles.css', '.'),
    ('resources/*', 'resources'),
    ('light.css', '.'),
    ('dark.css', '.'),
    ('mp_viewer_app.py', '.'),
    ('HeaderEditWindow.py', '.'),
    ('ArxSR.py', '.'),
    ('qrc_resources.py', '.')
    ],
    hiddenimports=['modelusage.model_usage',
    'modelcropper.model_cropper',
    'modelalign.model_align',
    'modelchar.model_char',
    'PyQt5', 'PyQt5.sip',
    'PIL', 'PIL.Image', 'Pillow',
    'mp_viewer_app',
    'HeaderEditWindow',
    'ArxSR',
    'GUIcomp',
    'scipy',
    'numpy',
    'astropy',
    'cv2',
    'shapely',
    'imutils',
    'matplotlib',
    'pytest'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ProAP22784884',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
